[features]
seeds = false
skip-lint = false
[programs.devnet]
solmail = "9s6iCh5fmBzGV8tc3ubiECvKy9cwarZvaGVbAaEb5uEc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/bennyhuang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

